using Microsoft.EntityFrameworkCore;
using Service1.Domain.Entities;

namespace Service1.Infrastructure.Data.DbContexts
{
    // DbContext : base class provided by Entity Framework Core for database contexts.
    public class ProductDbContext(DbContextOptions<ProductDbContext> options) : DbContext(options)
    {
        // Represents a collection of Product entities that can be queried from and saved to the database.
        public DbSet<Product> Products { get; set; }

        // This method is used to configure the database schema for the context.
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Maps the Product entity to a database table named "Products".
            modelBuilder.Entity<Product>().ToTable("Products");
            // Specifies that the primary key for the Product entity is the Id property.
            modelBuilder.Entity<Product>().HasKey(m => m.Id);
            // Configures the Id property to be generated by the database when a new Product entity is inserted (auto-increment).
            modelBuilder.Entity<Product>().Property(m => m.Id).ValueGeneratedOnAdd();
        }
    }
}